# Generated by Django 3.0.4 on 2020-06-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20200531_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klasa',
            name='imazhi',
            field=models.ImageField(upload_to='cat_images'),
        ),
        migrations.AlterField(
            model_name='lendet',
            name='imazhi_lendes',
            field=models.ImageField(upload_to='kurs_images'),
        ),
    ]
